#!/usr/bin/env node
/**
 * Inline the handful of Lucide icons the site actually uses.
 *
 * The pages used to load https://unpkg.com/lucide@latest — the complete icon
 * set, unpinned, on every page view, just to draw about two dozen glyphs. This
 * reads the same icons from the pinned `lucide-static` package and emits:
 *
 *   templates/schema-resume/partials/icons.html → one {{define "icon-<name>"}}
 *                                                 per glyph, for templates
 *   templates/schema-resume/js/vendor/icons.js  → runtime, for icons that
 *                                                 JavaScript creates
 *
 * The template side is a partial rather than a data file on purpose: ssg's
 * `safeHTML` renders Markdown, so geometry passed through it comes back wrapped
 * in a <p> and the icon does not draw. A {{define}} is emitted verbatim.
 *
 * Both are generated; both are gitignored. Run via `npm run build:assets`.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

const ICONS_DIR = join(dirname(require.resolve('lucide-static/package.json')), 'icons');
const PARTIAL_OUT = join(repoRoot, 'templates', 'schema-resume', 'partials', 'icons.html');
const JS_OUT = join(repoRoot, 'templates', 'schema-resume', 'js', 'vendor', 'icons.js');

/**
 * Lucide ships each icon as a licence comment followed by a complete <svg>
 * element, attributes one per line. Templates and the runtime both supply their
 * own <svg> wrapper so size and classes stay at the call site, so only the
 * inner geometry is kept.
 */
function innerGeometry(svg) {
    const body = svg.replace(/<!--[\s\S]*?-->/g, '');
    const start = body.indexOf('<svg');
    if (start === -1) {
        throw new Error('no <svg> element');
    }
    // The opening tag is multi-line; its own '>' is the first one after '<svg'.
    const opening = body.indexOf('>', start);
    const closing = body.lastIndexOf('</svg>');
    if (opening === -1 || closing === -1 || closing < opening) {
        throw new Error('unrecognised SVG shape');
    }
    return body.slice(opening + 1, closing).replace(/\s+/g, ' ').trim();
}

async function main() {
    const { icons: names } = JSON.parse(await readFile(join(repoRoot, 'tools', 'icons.json'), 'utf8'));

    const geometry = {};
    const missing = [];
    for (const name of names) {
        try {
            geometry[name] = innerGeometry(await readFile(join(ICONS_DIR, `${name}.svg`), 'utf8'));
        } catch {
            missing.push(name);
        }
    }

    if (missing.length > 0) {
        // A renamed upstream icon must fail the build rather than ship a page
        // with silent holes where the glyphs should be.
        throw new Error(
            `icons not found in lucide-static: ${missing.join(', ')}.\n` +
            'Lucide renames icons between majors — check the current name and update tools/icons.json.'
        );
    }

    await mkdir(dirname(PARTIAL_OUT), { recursive: true });
    await writeFile(PARTIAL_OUT, templatePartial(geometry));

    await mkdir(dirname(JS_OUT), { recursive: true });
    await writeFile(JS_OUT, runtimeModule(geometry));

    const bytes = Buffer.byteLength(JSON.stringify(geometry));
    console.log(`✅ icons: inlined ${names.length} glyphs (${(bytes / 1024).toFixed(1)} kB)`);
}

/**
 * One {{define}} per icon.
 *
 * Go templates cannot dispatch `{{ template }}` on a variable, so each glyph
 * gets its own define and call sites name it directly:
 *
 *     {{ template "icon-check" (dict "Size" 16) }}
 *     {{ template "icon-check" (dict "Size" 16 "Class" "text-muted") }}
 *
 * Icons are decorative — every call site pairs one with real text — so they
 * are hidden from assistive technology rather than labelled and read twice.
 */
function templatePartial(geometry) {
    const header = `{{/*
  Generated by tools/build-icons.mjs — do not edit.
  Icon geometry from Lucide (https://lucide.dev), ISC licensed.

  Usage: {{ template "icon-<name>" (dict "Size" 16) }}
  "Size" defaults to 24; "Class" is optional.
*/}}
`;

    const open = '<svg xmlns="http://www.w3.org/2000/svg" ' +
        'width="{{ if .Size }}{{ .Size }}{{ else }}24{{ end }}" ' +
        'height="{{ if .Size }}{{ .Size }}{{ else }}24{{ end }}" ' +
        'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
        'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" ' +
        'focusable="false"{{ with .Class }} class="{{ . }}"{{ end }}>';

    const defines = Object.entries(geometry)
        .map(([name, inner]) => `{{define "icon-${name}"}}${open}${inner}</svg>{{end}}`)
        .join('\n');

    return `${header}\n${defines}\n`;
}

function runtimeModule(geometry) {
    return `/*
 * Generated by tools/build-icons.mjs — do not edit.
 * Icon geometry from Lucide (https://lucide.dev), ISC licensed.
 */
(function (global) {
    'use strict';

    var GEOMETRY = ${JSON.stringify(geometry)};

    /**
     * Build an inline SVG string for one icon.
     *
     * Icons here are always decorative: every call site pairs them with real
     * text, so they are hidden from assistive technology rather than given a
     * label that would be read out twice.
     */
    function icon(name, size, className) {
        var geometry = GEOMETRY[name];
        if (!geometry) {
            return '';
        }
        return '<svg xmlns="http://www.w3.org/2000/svg" width="' + (size || 24) +
            '" height="' + (size || 24) + '" viewBox="0 0 24 24" fill="none" ' +
            'stroke="currentColor" stroke-width="2" stroke-linecap="round" ' +
            'stroke-linejoin="round" aria-hidden="true" focusable="false"' +
            (className ? ' class="' + className + '"' : '') + '>' + geometry + '</svg>';
    }

    global.srIcon = icon;
})(window);
`;
}

main().catch((error) => {
    console.error(`❌ build-icons: ${error.message}`);
    process.exitCode = 1;
});
