name: Release Packages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.1.0)'
        required: true
        type: string

env:
  VERSION: ${{ github.event.inputs.version || github.ref_name }}

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
            TAG="v${VERSION}"
          else
            TAG="${{ github.ref_name }}"
            VERSION="${TAG#v}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}"
          echo "Tag: ${TAG}"

  release-npm:
    name: Release NPM Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: packages/npm
        run: npm install

      - name: Run tests
        working-directory: packages/npm
        run: npm test

      - name: Publish to NPM
        working-directory: packages/npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

  release-python:
    name: Release Python Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        working-directory: packages/python
        run: python -m build

      - name: Publish to PyPI
        working-directory: packages/python
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        continue-on-error: true

  release-golang:
    name: Release Go Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download dependencies
        working-directory: packages/golang
        run: go mod download

      - name: Run tests
        working-directory: packages/golang
        run: go test -v ./...
        continue-on-error: true

      - name: Tag Go module
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "packages/golang/${{ needs.prepare.outputs.tag }}" || true
          git push origin "packages/golang/${{ needs.prepare.outputs.tag }}" || true
        continue-on-error: true

  release-java:
    name: Release Java Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: packages/java
        run: mvn clean package

      - name: Publish to Maven Central
        working-directory: packages/java
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        continue-on-error: true

  release-ruby:
    name: Release Ruby Gem
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Build gem
        working-directory: packages/ruby
        run: gem build schema-resume-validator.gemspec

      - name: Publish to RubyGems
        working-directory: packages/ruby
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push schema-resume-validator-*.gem
        continue-on-error: true

  release-php:
    name: Release PHP Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Validate composer.json
        working-directory: packages/php
        run: composer validate

      - name: Install dependencies
        working-directory: packages/php
        run: composer install --prefer-dist --no-progress

      - name: Create release note
        run: |
          echo "PHP package is published via Packagist automatically when tags are pushed"
          echo "Package will be available at: https://packagist.org/packages/schema-resume/validator"

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare, release-npm, release-python, release-golang, release-java, release-ruby, release-php]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Notes
        id: release_notes
        run: |
          cat << EOF > release_notes.md
          # Schema Resume ${{ needs.prepare.outputs.version }}

          ## Package Releases

          This release includes packages for multiple programming languages:

          ### NPM (JavaScript/TypeScript)
          \`\`\`bash
          npm install schema-resume-validator
          \`\`\`
          - Package: [schema-resume-validator](https://www.npmjs.com/package/schema-resume-validator)

          ### Python
          \`\`\`bash
          pip install schema-resume-validator
          \`\`\`
          - Package: [schema-resume-validator](https://pypi.org/project/schema-resume-validator/)

          ### Go
          \`\`\`bash
          go get github.com/tradik/schema-resume/validator@${{ needs.prepare.outputs.tag }}
          \`\`\`
          - Package: [github.com/tradik/schema-resume/validator](https://pkg.go.dev/github.com/tradik/schema-resume/validator)

          ### Java (Maven)
          \`\`\`xml
          <dependency>
              <groupId>org.schema-resume</groupId>
              <artifactId>schema-resume-validator</artifactId>
              <version>${{ needs.prepare.outputs.version }}</version>
          </dependency>
          \`\`\`
          - Package: [Maven Central](https://search.maven.org/artifact/org.schema-resume/schema-resume-validator)

          ### Ruby
          \`\`\`bash
          gem install schema-resume-validator
          \`\`\`
          - Package: [schema-resume-validator](https://rubygems.org/gems/schema-resume-validator)

          ### PHP (Composer)
          \`\`\`bash
          composer require schema-resume/validator
          \`\`\`
          - Package: [schema-resume/validator](https://packagist.org/packages/schema-resume/validator)

          ## Schema Files

          All packages include:
          - **schema.json** - Main JSON Schema
          - **meta-schema.json** - Meta-schema for validation
          - **context.jsonld** - JSON-LD context for semantic web integration
          - **schema-resume.xsd** - XML Schema Definition

          ## Links

          - **Website**: https://schema-resume.org/
          - **Documentation**: https://github.com/tradik/schema-resume
          - **Online Validator**: https://schema-resume.org/validator.html
          - **Changelog**: https://github.com/tradik/schema-resume/blob/main/CHANGELOG.md

          ## Support

          - Email: info@schema-resume.org or support@tradik.com
          - Issues: https://github.com/tradik/schema-resume/issues
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: Release ${{ needs.prepare.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
